# Use root/example as user/password credentials
version: '3.1'
services:
    database:
        image: mongo
        container_name: 'todo-mongo'
        environment: 
            MONGO_INITDB_DATABASE: admin
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: kumawat
        volumes:
            - ./createUser.js:/docker-entrypoint-initdb.d/createUser.js:ro
        ports: 
          - '28017:27017'
